const form=document.querySelector('#config'), msg=document.querySelector('#message'); let cfg={};
async function json(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw Error(data.detail||r.statusText);return data}
function render(c){cfg=c;form.innerHTML='';for(const [k,v] of Object.entries(c)){const label=document.createElement('label');label.textContent=k;const input=document.createElement('input');input.name=k;if(typeof v==='boolean'){input.type='checkbox';input.checked=v}else{input.value=v??'';input.dataset.type=typeof v}label.append(input);form.append(label)}}
async function status(){try{const s=await json('/api/status');const dbfs=typeof s.last_dbfs==='number'?`${s.last_dbfs.toFixed(1)} dBFS`:'waiting for audio';const gate=s.last_gated?'gated':'model active';const quiet=s.quiet_active?'quiet hours active':'quiet hours inactive';const model=(s.last_model_score??0).toFixed(3);const acoustic=(s.last_acoustic_score??0).toFixed(3);document.querySelector('#status').textContent=`${s.state} · ${s.bark_count} barks · combined ${s.last_bark_score.toFixed(3)} · model ${model} · acoustic ${acoustic} · ${dbfs} · ${gate} · ${quiet}`;document.querySelector('#top').innerHTML=(s.top_predictions||[]).map(p=>`<li>${p.label}: ${p.score.toFixed(3)}</li>`).join('');document.querySelector('#dog-scores').innerHTML=Object.entries(s.dog_scores||{}).map(([label,score])=>`<li>${label}: ${score.toFixed(3)}</li>`).join('')}catch(e){msg.textContent=e.message}}
document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>json('/api/simulate/'+b.dataset.count,{method:'POST'}).then(status).catch(e=>msg.textContent=e.message));
document.querySelector('#test').onclick=()=>json('/api/test-response',{method:'POST'}).then(status).catch(e=>msg.textContent=e.message);
document.querySelector('#browser-start').onclick=async()=>{try{await dogwatchBrowserDetector.start(cfg);document.querySelector('#browser-start').disabled=true;document.querySelector('#browser-stop').disabled=false}catch(e){msg.textContent='Browser detector failed: '+e.message}};
document.querySelector('#browser-stop').onclick=async()=>{await dogwatchBrowserDetector.stop();document.querySelector('#browser-start').disabled=false;document.querySelector('#browser-stop').disabled=true};
document.querySelector('#save').onclick=async()=>{const out={};for(const el of form.elements){out[el.name]=el.type==='checkbox'?el.checked:el.value===''?null:el.dataset.type==='number'?Number(el.value):el.value}try{render(await json('/api/config',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(out)}));msg.textContent='Saved.'}catch(e){msg.textContent='Not saved: '+e.message}};
json('/api/config').then(render);status();setInterval(status,1000);
